

const main = async () => {


    const challengeAddress = "0x4150943e81958bEEC795549cE8C160770A53002B"

    const ExploitFactory = await hre.ethers.getContractFactory("Exploit")
    const exploit = await ExploitFactory.deploy(challengeAddress)
    await exploit.deployed()

    

}




main()
.then(() => process.exit(0))
.catch((error) => {
  console.error(error);
  process.exit(1);
});